#!/bin/bash

export BASE_PACKAGES="\
	aria2 \
	bat \
	bluez-utils \
	btop \
	distrobox \
	cmake \
	ddcutil \
	cage \
	expect \
	exfatprogs \
	fakeroot \
	fastfetch \
	fd \
	firejail \
	freerdp \
	fzf \
	f2fs-tools \
	fuse-zip \
	git \
	git-lfs \
	gparted \
	haveged \
	htop \
	ibus-libpinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	ibus-rime \
	jq \
	lib32-libva \
	lib32-libva-intel-driver \
	libcec \
	libdisplay-info \
	libva-intel-driver \
	liquidctl \
	lrzip \
	lzip \
	modemmanager \
	nmon \
	otf-fira-mono \
	otf-fira-sans \
	otf-font-awesome \
	patch \
	podman \
	podman-compose \
	podman-docker \
	python-pyclip \
	python-pyudev \
	python-systemd \
	qtractor \
	ripgrep \
	screen \
	scx-scheds \
	scx-tools \
	shfmt \
	smartmontools \
	switcheroo-control \
	s-tui \
	ttf-dejavu \
	unace \
	v2ray \
	wlr-randr \
	xorg-server-xvfb \
	zoxide \
"

export EXTRA_PACKAGES="\
	antimicrox \
	chafa \
	deskflow \
	imagemagick \
	lact-libadwaita \
	mission-center \
	mpv \
	openrgb \
	poppler \
	rclone \
	remmina \
	solaar \
	tailscale \
	tuned-ppd \
	waydroid-helper \
	yazi \
"

export BASE_PACKAGES="$BASE_PACKAGES $EXTRA_PACKAGES"

export NVDIA_PACKAGES="\
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
	nvidia-container-toolkit \
"

export BASE_AUR_PACKAGES="\
	networkd-dispatcher \
	nbfc-linux \
	noto-fonts-cjk-fontconfig \
	onedrive-abraunegg \
	ludusavi-bin \
	rtl8821au-dkms-git \
	sx \
"

export EXTRA_AUR_PACKAGES="\
	adwsteamgtk \
	flatseal \
	moonlight-qt-axi \
	protonplus \
	protontricks \
	tsukimi-bin \
	waydroid-script-git \
"

export BASE_AUR_PACKAGES="$BASE_AUR_PACKAGES $EXTRA_AUR_PACKAGES"

export CORE_LOCAL_PACKAGES="\
	mangohud-sk-git \
	powerstation-git \
	skorionos-fastfetch-logo \
	steam-launch-manager \
	steam-removable-media-git \
	steamos-manager \
	steamos-powerbuttond \
	xonedo-sk-dkms \
	xone-dongle-firmware \
"
export BASE_LOCAL_PACKAGES="\
	$CORE_LOCAL_PACKAGES \
	davfs2 \
	rtl88x2bu-dkms-git \
"